version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - streamer_network
  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

    networks:
      - streamer_network

  # streamer_api_service:
  #   image: streamer_api:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - kafka
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #     - SPRING_KAFKA_CONSUMER_GROUP-ID=id-lookup-group
  #     - KAFKA_APPLICATION_ID=streamer-api-service
  #     - STREAMER_ID_TOPIC_NAME=STREAMER_ID_TOPIC
  #   networks:
  #     - streamer_network

networks:
  streamer_network:
